[packages.darwin]
taps = [
  "charmbracelet/tap",
  "joshmedeski/sesh",
  "leoafarias/fvm",
  "nikitabobko/tap",
]

brews = [
  "bat",
  "clang-format",
  "cmake",
  "cocoapods",
  "exiftool",
  "eza",
  "fvm",
  "fzf",
  "gh",
  "git",
  "glow",
  "go",
  "joshmedeski/sesh/sesh",
  "jq",
  "mas",
  "mods",
  "mosh",
  "nats-io/nats-tools/nats",
  "neovim",
  "ninja",
  "npm",
  "ripgrep",
  "ruby",
  "sqlc",
  "starship",
  "tmux",
  "vim",
  "wget",
  "yazi",
  "yt-dlp",
  "zoxide",
  "zsh",
]

casks = [
  "aerospace",
  "arc",
  "font-jetbrains-mono-nerd-font",
  "gcc-arm-embedded",
  "ghostty",
  "raycast",
  "slack",
  "tailscale",
]
